setwd("D:/Rdata")
owner.df <- read.csv("ownerExample.csv", header = TRUE)
str(owner.df)
install.packages("pROC")
library(pROC)
r <- roc(owner.df$Class, owner.df$Probability)
str(r)
plot.roc(r)
auc(r)
df<-read.csv("liftExample.csv")
str(df)
library(gains)
dim(df)
gain<-gains(df$actual, df$prob, groups=dim(df)[1])
gain
plot(c(0, gain$cume.pct.of.total*sum(df$actual)) ~ c(0, gain$cume.obs),
     xlab = "# cases", ylab = "Cumulative", main="Lift Chart", type="l")
lines(c(0, sum(df$actual)) ~ c(0, dim(df)[1]), col="red", lty=2)
gain<-gains(df$actual, df$prob)
barplot(gain$mean.resp/mean(df$actual), names.arg=gain$cume.obs)
